package project.project.map;

public enum Biome {
    LUSH_FOREST, SUNNY_PLAINS, DARK_WOODS, SNOWY_TUNDRA,
    SWAMPY_WETLANDS, AUTUMN_GROVE, FLOWERING_MEADOW,
    ROCKY_FLATS, DENSE_JUNGLE, DESERT_OASIS, DESERT,
    HAUNTED_WOODS, SAVANNA, ENCHANTED_GROVE, SPOOKY_VALLEY, OCEAN, DEEP_OCEAN
}
